apiVersion: v1
kind: Service
metadata:
  name: book-import
  labels:
    name: book-import
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 1313
      protocol: TCP
  selector:
    name: book-import